# TL;DR: YOU SHOULD DELETE THIS FILE
#
# This file was generated by Cucumber-Rails and is only here to get you a head start
# These step definitions are thin wrappers around the Capybara/Webrat API that lets you
# visit pages, interact with widgets and make assertions about page content.
#
# If you use these step definitions as basis for your features you will quickly end up
# with features that are:
#
# * Hard to maintain
# * Verbose to read
#
# A much better approach is to write your own higher level step definitions, following
# the advice in the following blog posts:
#
# * http://benmabey.com/2008/05/19/imperative-vs-declarative-scenarios-in-user-stories.html
# * http://dannorth.net/2011/01/31/whose-domain-is-it-anyway/
# * http://elabs.se/blog/15-you-re-cuking-it-wrong
#


require 'uri'
require 'cgi'
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "paths"))
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "selectors"))

module WithinHelpers
  def with_scope(locator)
    locator ? within(*selector_for(locator)) { yield } : yield
  end
end
World(WithinHelpers)

Given /^(?:|I )am on the (.+) page$/ do |page_name|
  visit path_to(page_name)
end

Given /the following shifts exist/ do |shifts_table|
  shifts_table.hashes.each do |shift|
    Shift.create(shift)

  end
end

When /^(?:|I )choose "([^"]*)" of shift: (.*)/ do |field, shifts|
  shifts.split(',').each do |shift|
    choose("#{shift}_#{field}")
  end
end

When /^(?:|I )press "([^"]*)"$/ do |button|
  click_button(button)
end

Then /^(?:|I )should be redirected to the (.+) page$/ do |page_name|
  visit path_to(page_name)
end

Then /^(?:|I )should see that "([^"]*)" equals (.*)$/ do |header, value|
  table_id = page.all("table#shifts td.#{header}").map(&:text)
  assert_equal table_id.to_s, value
end

